development:
  adapter: postgresql
  database: justnotes_dev
  username: postgres
  password: tron1pos
  host: localhost

test:
  adapter: postgresql
  database: justnotes_test
  username: postgres
  password: tron1pos
  host: localhost
