development:
  adapter: postgresql
  encoding: unicode
  database: just-notes
  pool: 100
  username: davids

test:
  adapter: postgresql
  encoding: unicode
  database: just-notes
  pool: 100

production:
  adapter: postgresql
  encoding: unicode
  database: just-notes
  pool: 100
